// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdVRsAiIkjGAy5Iw1BgAxdht0XHL1tvL8',
    appId: '1:751886869559:web:0a7c1ec2347419e92c0bb2',
    messagingSenderId: '751886869559',
    projectId: 'mastering-fire',
    authDomain: 'mastering-fire.firebaseapp.com',
    storageBucket: 'mastering-fire.firebasestorage.app',
    measurementId: 'G-ZXW3802V2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBakFskhDKWfejvEWferLOKrXea5dxIwaU',
    appId: '1:751886869559:android:288df9f0ada49bcc2c0bb2',
    messagingSenderId: '751886869559',
    projectId: 'mastering-fire',
    storageBucket: 'mastering-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl5RbI3cYXnuO0Vo7lBuhixALD_DllP0c',
    appId: '1:751886869559:ios:37f4653a6e2d4f622c0bb2',
    messagingSenderId: '751886869559',
    projectId: 'mastering-fire',
    storageBucket: 'mastering-fire.firebasestorage.app',
    iosClientId: '751886869559-j44vss45tbv11rih786ommcaq1r7frqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl5RbI3cYXnuO0Vo7lBuhixALD_DllP0c',
    appId: '1:751886869559:ios:37f4653a6e2d4f622c0bb2',
    messagingSenderId: '751886869559',
    projectId: 'mastering-fire',
    storageBucket: 'mastering-fire.firebasestorage.app',
    iosClientId: '751886869559-j44vss45tbv11rih786ommcaq1r7frqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdVRsAiIkjGAy5Iw1BgAxdht0XHL1tvL8',
    appId: '1:751886869559:web:e678ad3de487665f2c0bb2',
    messagingSenderId: '751886869559',
    projectId: 'mastering-fire',
    authDomain: 'mastering-fire.firebaseapp.com',
    storageBucket: 'mastering-fire.firebasestorage.app',
    measurementId: 'G-NSQZ83YCTY',
  );

}